name: total_share
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: 4.6.1
  qr_flutter: 4.0.0
  network_info_plus: 2.1.3
  path_provider: 2.0.9
  url_launcher: 6.0.20
  barcode_scan2: 4.2.0
  file_picker: 4.5.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
